// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHwMU78vByLKbULU0CmRQ91YNJqHvduE',
    appId: '1:893307652632:web:f528e13f4f548ae88d116d',
    messagingSenderId: '893307652632',
    projectId: 'gerd-d8a5e',
    authDomain: 'gerd-d8a5e.firebaseapp.com',
    storageBucket: 'gerd-d8a5e.appspot.com',
    measurementId: 'G-Y43YHXRXND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJp4PX9IQ6fuljtk8yXnib6ZgZm6zbxUI',
    appId: '1:893307652632:android:08fe0741c3082e338d116d',
    messagingSenderId: '893307652632',
    projectId: 'gerd-d8a5e',
    storageBucket: 'gerd-d8a5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-6PhmBe6g89DxQ_a-nQOyERKRhCGnMM',
    appId: '1:893307652632:ios:0bc40d9f5cd710ad8d116d',
    messagingSenderId: '893307652632',
    projectId: 'gerd-d8a5e',
    storageBucket: 'gerd-d8a5e.appspot.com',
    iosClientId: '893307652632-q2f8nhovgvghjtuoa2743nstjvfcf0e4.apps.googleusercontent.com',
    iosBundleId: 'com.gerd.app',
  );
}
